# Generated by Django 5.2.7 on 2025-10-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_list_auctions_comment_bids_watchlist_watchlist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_auctions',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
