# Generated by Django 5.2.7 on 2025-10-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_list_auctions_comment_bids_watchlist_watchlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_auctions',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='auction_photos/'),
        ),
        migrations.AlterField(
            model_name='list_auctions',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='list_auctions',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
