# Generated by Django 5.2.7 on 2025-10-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_list_auctions_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_auctions',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
