# Generated by Django 5.2.7 on 2025-10-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_list_auctions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_auctions',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='auction_photos/'),
        ),
    ]
