# Generated by Django 5.2.7 on 2025-10-13 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_comment_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist_items',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Watchlist_Items', to='auctions.list_auctions'),
        ),
    ]
