# Generated by Django 5.2.7 on 2025-10-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_watchlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='count_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
