# Generated by Django 5.2.7 on 2025-10-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist_count_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='count_items',
        ),
    ]
