# Generated by Django 5.2.7 on 2025-11-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_remove_watchlist_count_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="list_auctions",
            name="number_of_bids",
            field=models.IntegerField(default=0),
        ),
    ]
