# Generated by Django 5.2.7 on 2025-11-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_list_auctions_number_of_bids"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="number_of_comments",
            field=models.IntegerField(default=0),
        ),
    ]
