# Generated by Django 5.2.7 on 2025-11-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_comment_number_of_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="number_of_comments",
        ),
    ]
