# Generated by Django 5.2.7 on 2025-11-05 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_remove_comment_number_of_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="list_auctions",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
